[project]
name = "hybrid-r-cnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "=", email = "=" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.14,<0.10.0"]
build-backend = "uv_build"
